# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"connector": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://maimanuel.github.io/bitcoin_twitter/"

git_url = "https://github.com/maimanuel/bitcoin_twitter/tree/master/"

def custom_doc_links(name): return None
