# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://manuelmai.github.io/bitcoin_twitter/"

git_url = "https://github.com/manuelmai/bitcoin_twitter/tree/master/"

def custom_doc_links(name): return None
